### ISSUE TITLE
Is there a normalize option in parameters.yaml under module "Pyaflowa Preprocess"

### ISSUE THREAD

**Issue by yhc1999mercy** [adjtomo/seisflows#250]
Seisflows version: 3.5.1
pyatoa version: 0.4.2
pyflex version: 0.2.0

I'm running a FWI in specfem3D by using seisflows. During the "EVALUATE INITIAL MISFIT" phase, It can't find windows in misfit quantification. 
```
2025-05-19 10:16:46 [DEBU] | quantifying misfit with 'Pyaflowa'
2025-05-19 10:16:48 [DEBU] | found 6 obs and 6 syn waveforms for given paths
2025-05-19 10:16:48 [INFO] | 6 traces matching between `obs` and `syn`
2025-05-19 10:16:56 [INFO] | 000000; misfit=0.00E+00; number of windows=0
2025-05-19 10:16:56 [WARN] | 0 windows found, will not normalize raw misfit
2025-05-19 10:17:26 [INFO] | FINISH QUANTIFY MISFIT: 000000
2025-05-19 10:17:28 [INFO] | misfit f_new (i01s00) = 0.000E+00
```
Therefore, when I use pyatoa independently to do misfit quantification, I found that a normalization-related parameter needs to be provided during preprocessing.
`mgmt.preprocess(which="both", filter=True, normalize_to='obs')`
after preprocess、standardize, I can finally get the misfit. But I found there is't a normalize option in parameters.yaml if I set "preprocess : pyaflowa"
```
# =============================================================================
#
#    Pyaflowa Preprocess [Preprocess Base]
#    -------------------------------------
#    Preprocessing and misfit quantification using Python's Adjoint Tomography
#    Operations Assistant (Pyatoa)
#
#    Parameters
#    ----------
#    :type min_period: float
#    :param min_period: Minimum filter corner in unit seconds. Bandpass
#        filter if set with `max_period`, highpass filter if set without
#    `max_period`, no filtering if not set and `max_period also not set
#    :type pyflex_parameters: dict
#    :param pyflex_parameters: overwrite for Pyflex parameters defined
#        in the Pyflex.Config object. Incorrectly defined argument names
#        will raise a TypeError. See Pyflex docs for detailed parameter defs:
#        http://adjtomo.github.io/pyflex/#config-object
#    :type pyadjoint_parameters: dict
#    :param pyadjoint_parameters: overwrite for Pyadjoint parameters defined
#        in the Pyadjoint.Config object for the given `adj_src_type`.
#        Incorrectly defined argument names will raise a TypeError. See
#        Pyadjoint docs for detailed parameter definitions:
#        https://adjtomo.github.io/pyadjoint/
#    :type fix_windows: bool or str
#    :param fix_windows: How to address misfit window evaluation at each
#        evaluation. Options to re-use misfit windows collected during an
#        inversion, available options:
#        [True, False, 'ITER', 'ONCE']
#        True: Re-use windows after first evaluation (i01s00);
#        False: Calculate new windows each evaluation;
#        'ITER': Calculate new windows at first evaluation of
#        each iteration (e.g., i01s00... i02s00...
#        'ONCE': Calculate new windows at first evaluation of
#        the workflow, i.e., at self.par.BEGIN
#    :type revalidate: bool
#    :param revalidate: Only used if `fix_windows` is True, ITER or ONCE. Windows
#        that are retrieved from datasets will be revalidated against parameters
#        in the Config object (ccshift, dlna, etc.), and rejected if they fall 
#        outside defined bounds. If False, windows will not be revalidated. 
#        Caution is advised with this parameter as event misfit may be 
#        artificially reducedby removing a significant number of windows, which
#        is possible when `revalidate`==True
#    :type adj_src_type: str
#    :param adj_src_type: Adjoint source type to evaluate misfit, defined by
#        Pyadjoint. See `pyadjoint.config.ADJSRC_TYPES` for detailed options list
#        - 'waveform': waveform misfit function
#        - 'convolution': convolution misfit function
#        - 'exponentiated_phase': exponentiated phase from Yuan et al. 2020
#        - 'cc_traveltime': cross-correlation traveltime misfit
#        - 'multitaper': multitaper misfit function
#    :type plot_waveforms: bool
#    :param plot_waveforms: plot waveform figures and source receiver maps during
#        the preprocessing stage. Maps require metadata, and if they are not
#        provided then only waveforms + windows + adjoint sources will be plotted
#    :type preprocess_log_level: str
#    :param preprocess_log_level: Log level to set Pyatoa, Pyflex, Pyadjoint.
#        Available: ['null': no logging, 'warning': warnings only,
#        'info': task tracking, 'debug': log all small details (recommended)]
#    :type unit_output: str
#    :param unit_output: Data units. Must match the synthetic output of
#        external solver. Available: ['DISP': displacement, 'VEL': velocity,
#        'ACC': acceleration]. Requires metadata.
#    :type export_datasets: bool
#    :param export_datasets: periodically save the output ASDFDataSets which
#        contain data, metadata and results collected during the
#        preprocessing procedure
#    :type export_figures: bool
#    :param export_figures: periodically save the output basemaps and
#        data-synthetic waveform comparison figures
#    :type export_log_files: bool
#    :param export_log_files: periodically save log files created by Pyatoa
#
#        
# =============================================================================
min_period: 2.0
max_period: 5.0
fix_windows: False
revalidate: False
adj_src_type: cc_traveltime
plot_waveforms: True
preprocess_log_level: DEBUG
pyflex_parameters: 
  stalta_waterlevel: 0.07
  tshift_acceptance_level: 10.0
  tshift_reference: 0.0
  dlna_acceptance_level: 1.3
  dlna_reference: 0.0
  cc_acceptance_level: 0.7
  s2n_limit: 1.5
  earth_model: ak135
  min_surface_wave_velocity: 3.0
  max_time_before_first_arrival: 50.0
  c_0: 1.0
  c_1: 1.5
  c_2: 0.0
  c_3a: 4.0
  c_3b: 2.5
  c_4a: 2.0
  c_4b: 6.0
  check_global_data_quality: False
  snr_integrate_base: 3.5
  snr_max_base: 3.0
  noise_start_index: 0
  noise_end_index: null
  signal_start_index: null
  signal_end_index: -1
  window_weight_fct: null
  window_signal_to_noise_type: amplitude
  resolution_strategy: interval_scheduling
pyadjoint_parameters: 
  taper_type: hann
  taper_percentage: 0.3
  measure_type: dt
  use_cc_error: True
  dt_sigma_min: 1.0
  dlna_sigma_min: 0.5
export_datasets: True
export_figures: True
export_log_files: True
obs_data_format: SAC
```
I wonder if the error was caused by not to normalize the obs_data and syn_data. I hope someone can help me clarify this.
